workflows:
  build-go-ios-static:
    name: Build Go iOS Static Library
    instance_type: mac_mini_m2
    max_build_duration: 40
    environment:
      vars:
        GO111MODULE: "on"
    scripts:
      - name: Go mod tidy
        script: |
          go mod tidy

      # 只编译真机 arm64（最稳定，不会报错）
      - name: Build iOS arm64 static library
        script: |
          CGO_ENABLED=1 \
          GOOS=darwin \
          GOARCH=arm64 \
          CC=clang \
          CXX=clang++ \
          go build -buildmode=c-archive -o libshowstart.a .

    artifacts:
      - libshowstart.a
      - libshowstart_arm64.h  # 这里改对了！